minecraft_version=1.21.4
minecraft_title=1.21.4
minecraft_targets=1.21.4
java_version=21
fabric_api_version=0.119.4+1.21.4
modmenu_version=13.0.4
neoforge_version=21.4.157
neoforge_loader_range=[4,)
neoforge_version_range=[21.4,)