mod.mc_title=1.21.11
mod.mc_targets=1.21.11
mod.java_version=21
dep.minecraft.fabric=1.21.11
dep.minecraft.neoforge=1.21.11
dep.fabric_loader=0.19.2
dep.fabric_api_version=0.141.3+1.21.11
dep.modmenu_version=17.0.0
dep.neoforge_loader=21.11.42
dep.neoforge_loader_range=[4,)
dep.neoforge_version_range=[21.11,)
