minecraft_version=26.1.2
minecraft_title=26.1
minecraft_targets=>=26.1 <26.2
java_version=25
fabric_loader_version=0.19.2
fabric_api_version=0.148.0+26.1.2
modmenu_version=18.0.0-alpha.8
neoforge_version=26.1.2.36-beta
neoforge_loader_range=[2,)
neoforge_version_range=[26,)