mod.mc_title=26.1
mod.mc_targets=>=26.1 <26.2
mod.java_version=25
dep.minecraft.fabric=26.1.2
dep.minecraft.neoforge=26.1.2
dep.fabric_loader=0.19.2
dep.fabric_api_version=0.148.0+26.1.2
dep.modmenu_version=18.0.0-alpha.8
dep.neoforge_loader=26.1.2.36-beta
dep.neoforge_loader_range=[2,)
dep.neoforge_version_range=[26,)
